/*
 * Copyright 2010-2014 OpenXcom Developers.
 *
 * This file is part of OpenXcom.
 *
 * OpenXcom is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenXcom is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenXcom. If not, see <http://www.gnu.org/licenses/>.
 */

#include "StartState.h"

#include <SDL_mixer.h>
#include <SDL_syswm.h>
#include <SDL_thread.h>

//kL #include "../version.h"

#include "ErrorMessageState.h"
#include "IntroState.h"
#include "MainMenuState.h"

#include "../Engine/Action.h"
#include "../Engine/Exception.h"
#include "../Engine/Font.h"
#include "../Engine/Game.h"
#include "../Engine/Language.h"
#include "../Engine/Logger.h"
#include "../Engine/Music.h"
#include "../Engine/Options.h"
#include "../Engine/Palette.h"
#include "../Engine/Screen.h"
#include "../Engine/Sound.h"
//kL #include "../Engine/Timer.h"

#include "../Interface/FpsCounter.h"
#include "../Interface/Cursor.h"
//kL #include "../Interface/Text.h"

#include "../Resource/XcomResourcePack.h"

#include "../Ruleset/Ruleset.h"


namespace OpenXcom
{

LoadingPhase StartState::loading;
std::string StartState::error;


/**
 * Initializes all the elements in the Loading screen.
 * @param game Pointer to the core game.
 */
StartState::StartState(Game* game)
	:
		State(game)
{
	// updateScale() uses newDisplayWidth/Height and needs to be set ahead of time
//kL	Options::newDisplayWidth	= Options::displayWidth;
//kL	Options::newDisplayHeight	= Options::displayHeight;

//kL	Options::baseXResolution = Options::displayWidth;
//kL	Options::baseYResolution = Options::displayHeight;
//kL	_game->getScreen()->resetDisplay(false);

	int
		dx = (Options::baseXResolution - 320) / 2,	// kL
		dy = (Options::baseYResolution - 200) / 2;	// kL
	_surface = new Surface(320, 200, dx, dy);		// kL

	_thread = 0;
	loading = LOADING_STARTED;
	error = "";

	// kL_begin: Old Loading screen ... pre 2014 may 26.
	// Set palette (set to {0} here to ensure all fields are initialized)
	SDL_Color bnw[3] = {{0}};
	bnw[0].r = 0;
	bnw[0].g = 0;
	bnw[0].b = 0;
	bnw[1].r = 255;
	bnw[1].g = 255;
	bnw[1].b = 255;
	bnw[2].r = 255;
	bnw[2].g = 255;
	bnw[2].b = 0;
	setPalette(bnw, 0, 3);

	add(_surface);

	_surface->drawString(120, 96, "Loading...", 1);

	_game->getCursor()->setVisible(false);
	_game->getFpsCounter()->setVisible(false);
	// kL_end.

/*kL
	_font = new Font();
	_font->loadTerminal();

	_text	= new Text(
					Options::baseXResolution,
					Options::baseYResolution,
					0,
					0);
	_cursor	= new Text(
					_font->getWidth(),
					_font->getHeight(),
					0,
					0);
	_timer	= new Timer(150);

	setPalette(_font->getSurface()->getPalette(), 0, 2);

	add(_text);
	add(_cursor);

	_text->initText(_font, _font, 0);
	_text->setColor(0);
	_text->setWordWrap(true);
//	_text->setText(L"Why hello there, I am a custom monoscaped bitmap font, yet I can still take advantage of wordwrapping and all the bells and whistles that regular text does, because I am actually being generated by a regular Text, golly gee whiz, we sure are living in the future now!\n\n!\"#$%&'()*+,-./0123456789:;<=>?\n@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_\n`abcdefghijklmnopqrstuvwxyz{|}~\n\nLoading OpenXcom 0.9...");

	_cursor->initText(_font, _font, 0);
	_cursor->setColor(0);
	_cursor->setText(L"_");

	_timer->onTimer((StateHandler)& StartState::blinkCursor);
	_timer->start();

	// Hide UI
	_game->getCursor()->setVisible(false);
	_game->getFpsCounter()->setVisible(false);

	if (Options::reload)
	{
		addLine(L"Restarting...");
		addLine(L"");
	}
	else
	{
		addLine(L"C:\\GAMES\\OPENXCOM>openxcom");
		addLine(L"");
		addLine(L"OpenXcom initialisation");
		addLine(L"");

		if (Options::mute)
			addLine(L"No Sound Detected");
		else
		{
			addLine(L"SoundBlaster Sound Effects");
			addLine(L"SoundBlaster Music");
			addLine(L"Base Port 220  Irq 5  Dma 1");
		}

		addLine(L"");
	} */
}

/**
 * Kill the thread in case the game is quit early.
 */
StartState::~StartState()
{
	if (_thread != 0)
		SDL_KillThread(_thread);

//kL	delete _font;
//kL	delete _timer;
}

/**
 * Reset and reload data.
 */
void StartState::init()
{
	State::init();

	// Silence!
	Sound::stop();
	Music::stop();

	_game->setResourcePack(0);
	if (!Options::mute
		&& Options::reload)
	{
		Mix_CloseAudio();
		_game->initAudio();
	}

/*kL
	std::wostringstream ss;
	ss << L"Loading OpenXcom " << Language::utf8ToWstr(OPENXCOM_VERSION_SHORT) << Language::utf8ToWstr(OPENXCOM_VERSION_GIT) << "...";
	addLine(ss.str()); */

	// Load the game data in a separate thread
	_thread = SDL_CreateThread(
							load,
							(void*)_game);

	if (_thread == 0)
	{
		// If we can't create the thread, just load it as usual
		load((void*)_game);
	}
}

/**
 * If the loading fails, it shows an error, otherwise moves on to the game.
 */
void StartState::think()
{
	State::think();
//kL	_timer->think(this, 0);

	switch (loading)
	{
		case LOADING_FAILED:
			flash();

			// kL_begin: Old Loading ... screen.
			_surface->clear();
			_surface->drawString(1, 9, "ERROR:", 2);
			_surface->drawString(1, 17, error.c_str(), 2);
			_surface->drawString(1, 49, "Make sure you installed OpenXcom", 1);
			_surface->drawString(1, 57, "correctly.", 1);
			_surface->drawString(1, 73, "Check the requirements and", 1);
			_surface->drawString(1, 81, "documentation for more details.", 1);
			_surface->drawString(75, 183, "Press any key to quit", 1);
			// kL_end.

/*kL
			addLine(L"");
			addLine(L"ERROR: " + Language::utf8ToWstr(error));
			addLine(L"Make sure you installed OpenXcom correctly.");
			addLine(L"Check the wiki documentation for more details."); */

			loading = LOADING_DONE;
		break;
		case LOADING_SUCCESSFUL:
			flash();

/*kL
			addLine(L"");
			addLine(L"OpenXcom initialised"); */

			Log(LOG_INFO) << "OpenXcom started!";
			if (!Options::reload
				&& Options::playIntro)
			{
				bool letterbox = Options::keepAspectRatio;
				Options::keepAspectRatio = true;

//kL				Options::baseXResolution = Screen::ORIGINAL_WIDTH;
//kL				Options::baseYResolution = Screen::ORIGINAL_HEIGHT;
//kL				_game->getScreen()->resetDisplay(false);

				_game->setState(new IntroState(
											_game,
											letterbox));
			}
			else
			{
				// This uses baseX/Y options for Geoscape & Basescape:
//				Options::baseXResolution = Options::baseXGeoscape; // kL
//				Options::baseYResolution = Options::baseYGeoscape; // kL
				// This sets Geoscape and Basescape to default (320x200) IG and the config.
/*kL			Screen::updateScale(
								Options::geoscapeScale,
								Options::geoscapeScale,
								Options::baseXGeoscape,
								Options::baseYGeoscape,
								true); */
//				_game->getScreen()->resetDisplay(false);

				State* state = new MainMenuState(_game);
				_game->setState(state);

				if (!Options::badMods.empty()) // Check for mod loading errors
				{
					std::wostringstream error;
					error << tr("STR_MOD_UNSUCCESSFUL") << L'\x02';
					for (std::vector<std::string>::iterator
							i = Options::badMods.begin();
							i != Options::badMods.end();
							++i)
					{
						error << Language::fsToWstr(*i) << L'\n';
					}

					Options::badMods.clear();

					_game->pushState(new ErrorMessageState(
														_game,
														error.str(),
														state->getPalette(),
														Palette::blockOffset(8)+10,
														"BACK01.SCR",
														6));
				}

				Options::reload = false;
			}

			_game->getCursor()->setVisible(true);
			_game->getFpsCounter()->setVisible(Options::fpsCounter);
		break;

		default:
		break;
	}
}

/**
 * The game quits if the player presses any key when an error
 * message is on display.
 * @param action Pointer to an action.
 */
void StartState::handle(Action *action)
{
	State::handle(action);
	if (loading == LOADING_DONE)
	{
		if (action->getDetails()->type == SDL_KEYDOWN)
			_game->quit();
	}
}

/**
 * Notifies the user that maybe he should have a look.
 */
void StartState::flash()
{
#ifdef _WIN32
	SDL_SysWMinfo wminfo;
	SDL_VERSION(&wminfo.version)
	if (SDL_GetWMInfo(&wminfo))
	{
		HWND hwnd = wminfo.window;
		FlashWindow(hwnd, true);
	}
#endif
}

/**
 * Blinks the cursor on the terminal output.
 */
/*kL void StartState::blinkCursor()
{
	_cursor->setVisible(!_cursor->getVisible());
} */

/**
 * Adds a line of text to the terminal and moves
 * the cursor appropriately.
 */
/*kL void StartState::addLine(const std::wstring& str)
{
	_output << L"\n" << str;
	_text->setText(_output.str());

	int
		y = _text->getTextHeight() - _font->getHeight(),
		x = _text->getTextWidth(y / _font->getHeight());
	_cursor->setX(x);
	_cursor->setY(y);
} */

/**
 * Loads game data and updates status accordingly.
 * @param game_ptr Pointer to the game.
 */
int StartState::load(void* game_ptr)
{
	Game* game = (Game*)game_ptr;
	try
	{
		Log(LOG_INFO) << "Loading ruleset...";
		game->loadRuleset();
		Log(LOG_INFO) << "Ruleset loaded.";

		Log(LOG_INFO) << "Loading resources...";
		Ruleset* ruleset = game->getRuleset();		// kL
		game->setResourcePack(new XcomResourcePack(	// kL sza_MusicRules, sza_ExtraMusic
												ruleset->getMusic(),
												ruleset->getExtraSprites(),
												ruleset->getExtraSounds(),
												ruleset->getExtraMusic()));
//kL		game->setResourcePack(new XcomResourcePack(
//kL												game->getRuleset()->getExtraSprites(),
//kL												game->getRuleset()->getExtraSounds()));
		Log(LOG_INFO) << "Resources loaded.";

		Log(LOG_INFO) << "Loading language...";
		game->defaultLanguage();
		Log(LOG_INFO) << "Language loaded successfully.";

		loading = LOADING_SUCCESSFUL;
	}
	catch (Exception &e)
	{
		error = e.what();
		Log(LOG_ERROR) << error;

		loading = LOADING_FAILED;
	}

	return 0;
}

}
